### ISSUE TITLE
Incompatibility with Create

### ISSUE THREAD

**Issue by SpongeGuy** [seymourimadeit/goat-horn-block#1]
This is such a cool concept for a mod, and the fact that you've enabled it to work with the voice chat mod is dope af. I tested it with the create mod to see if it worked with their redstone links, and there might be an incompatibility I thought you would want to know about.

Here is the paste from the server: [link](https://hastebin.com/share/akavaberox.bash)
running with create-1.19.2-0.5.0.i.jar btw

If you need more information, let me know.

**Comment by seymourimadeit** [comment]
https://modrinth.com/mod/placeable-goat-horns/version/1.19.4-1.0.1

Should be uploaded on curseforge by tommorow morning, if you need them early the files are on modrinth.
