### ISSUE TITLE
[Feature] Simple Voice Chat Integration

### ISSUE THREAD

**Issue by Skidamek** [seymourimadeit/goat-horn-block#2]
I think it would be super dope to make it work with voice chat mod like [Simple Voice Chat](https://modrinth.com/plugin/simple-voice-chat) e.g. you could build train station with create and make on it like speakers from this mod with goat horns and someone who is working on that station could say that some train is arriving in a min at platform 2, something like that :)

**Comment by Skidamek** [comment]
Ah, i didn't check the code before, now i see, is it already implemented?

**Comment by seymourimadeit** [comment]
Yes
