### ISSUE TITLE
Incompatibility with Yung's Better Nether Fortresses

### ISSUE THREAD

**Issue by Emerald310** [seymourimadeit/goat-horn-block#7]
Hi, thanks for the fun mod, but here's a problem I've been having;
Loading chunks in the nether which should include a fortress from Yung' Better Fortresses, freezes the game. 
Unsure if there's a technical word for it, since it's not crashing the game to desktop, but most functions of the game such as mob AI, chunk rendering et.c, freezes. Quitting the game will also result in being stuck in a loading menu.

This issue is occurring using just the combination of YungsBetterNetherFortresses 2.0.5 for 1.20, YungsApi 4.0.2 for 1.20, and Goat Horn Block 1.2.2. All running on Forge 47.2.0 for 1.20.

I was able to consistently reproduce this issue by using that combination of mods, loading into the nether in a world, using /locate structure to find a (Yung's) fortress, and approaching the location of the returned coordinates. Doing so will freeze the game as described, once the fortress tries to generate.

It's also maybe worth noting that I had a similar issue occur within a larger set of mods, but for Yung's Better Strongholds, however, clearing my .minecraft of any old config files seemed to fix that issue. Probably unrelated.

Also worth mentioning that I have no clue if this is an issue with goat horn block, or with Yung's fortresses. I apologize if it is the latter, or if I'm wasting your time.

It doesn't generate a crash log, since the only way to exit the game seems to be killing it through task manager when the problem occurs, but do let me know if I can provide any more info. Thanks.

**Comment by seymourimadeit** [comment]
Please send a log generated by the [spark mod](https://www.curseforge.com/minecraft/mc-mods/spark) for further diagnosis.

**Comment by Emerald310** [comment]
I'm sorry, but I've never used Spark before and it seems there's quite a few diagnostic tools included. How would I go about generating a log useful for this issue? By generating a heapdump, or profile..? Thanks for the prompt reply anyways.

**Comment by seymourimadeit** [comment]
I suggest right as you join the game you type in /spark profiler start, and then /spark profiler open (it will open a link that you can view live for the game), then recreate the issue.

A heapdump would provide a similar level of diagnosis needed to investigate this issue.

**Comment by Emerald310** [comment]
Apologies for the delay, here's a spark profile from joining a new world, starting the profile, entering the nether, only for a fortress to (attempt to) load nearby, then killing the minecraft process after a bit. 
I also created a heapdump, by re-entering the world and going through the portal, then using the spark command immediately.
However, the heapdump is almost a gigabyte for some reason, so I'm not sure how I'd go about sending that through.
Regardless, here's the spark profile file (zipped so I can attach it), hopefully this helps, lmk if I can do anything else.
[spark profile.zip](https://github.com/seymourimadeit/goat-horn-block/files/14276256/spark.profile.zip)

**Comment by BugmanBugman** [comment]
Can check it out it happens to me

**Comment by seymourimadeit** [comment]
> Apologies for the delay, here's a spark profile from joining a new world, starting the profile, entering the nether, only for a fortress to (attempt to) load nearby, then killing the minecraft process after a bit. I also created a heapdump, by re-entering the world and going through the portal, then using the spark command immediately. However, the heapdump is almost a gigabyte for some reason, so I'm not sure how I'd go about sending that through. Regardless, here's the spark profile file (zipped so I can attach it), hopefully this helps, lmk if I can do anything else. [spark profile.zip](https://github.com/seymourimadeit/goat-horn-block/files/14276256/spark.profile.zip)

Forgot to reply yesterday but I'm investigating it right now and should release a jar file here for you to test it out before I release it

**Comment by seymourimadeit** [comment]
ok here's the .zip file, just grab the .jar from here and report if the bug still happens or not
[zipfilesogithubdoesntcomplain.zip](https://github.com/seymourimadeit/goat-horn-block/files/14307313/zipfilesogithubdoesntcomplain.zip)

**Comment by Emerald310** [comment]
Hi, unfortunately, I tried reproducing the original problem with the new file and the problem still happened consistently when loading in fortress chunks. Thanks for looking into it though.

**Comment by seymourimadeit** [comment]
damn

heres another one 
[electricboogalo.zip](https://github.com/seymourimadeit/goat-horn-block/files/14321399/electricboogalo.zip)

**Comment by seymourimadeit** [comment]
[qwerth.zip](https://github.com/seymourimadeit/goat-horn-block/files/14324835/qwerth.zip)

I did some self-testing with this .jar and the bug seems to be fixed, however I'd still like some second opinions

**Comment by Emerald310** [comment]
> [qwerth.zip](https://github.com/seymourimadeit/goat-horn-block/files/14324835/qwerth.zip)
> 
> I did some self-testing with this .jar and the bug seems to be fixed, however I'd still like some second opinions

Works for me. Tested the original problem a few times and didn't have any crashes. Thanks for working on it.
